### ISSUE TITLE
Pause key gives wrong code. setLock(.) doesn't work in setup()

### ISSUE THREAD

**Issue by pensigma** [techpaul/PS2KeyAdvanced#26]
I'm using V1.0.9 and when I press the Pause key it gives me 6 (PS2_KEY_L_SHIFT) instead of 5 (PS2_KEY_PAUSE).
In PS2KeyAdvanced.cpp line 674 I see
`return  PS2_KEY_PAUSE + _FUNCTION;`

Is there a reason for the + _FUNCTION that results in 5 + 1 = 6?

Also, if I put in `setup()` the following:
```
keyboard.begin( . );
keyboard.setLock(PS2_LOCK_NUM);
```

When the Arduino is initially powered up, the Num Lock doesn't turn on until I press a key on the keyboard.
I also tried `setLock(PS2_LOCK_NUM)` and `resetKey()` inside `loop()` but they don't work either until a key has been pressed on the keyboard.
`resetKey()` can also cause a hang unless a key has been pressed beforehand.
I can replicate the issue by turning the Arduino off then on.

**Comment by techpaul** [comment]
First of all WHICH "Arduino" are you using as that is one of over 30 boards historically.

> I'm using V1.0.9 and when I press the Pause key it gives me 6 (PS2_KEY_L_SHIFT) instead of 5 (PS2_KEY_PAUSE). In PS2KeyAdvanced.cpp line 674 I see `return PS2_KEY_PAUSE + _FUNCTION;`
> 
> Is there a reason for the + _FUNCTION that results in 5 + 1 = 6?

That is a mistake should NOT be adding _FUNCTION

Noted for next relaase

> 
> Also, if I put in `setup()` the following:
> ```
> keyboard.begin( . );
> keyboard.setLock(PS2_LOCK_NUM);
> ```
>
> When the Arduino is initially powered up, the Num Lock doesn't turn on until I press a key on the keyboard. I also tried `setLock(PS2_LOCK_NUM)` and `resetKey()` inside `loop()` but they don't work either until a key has been pressed on the keyboard. `resetKey()` can also cause a hang unless a key has been pressed beforehand. I can replicate the issue by turning the Arduino off then on.

WHY are you trying to drive the keyboard SO quickly it takes over 500 ms for the device to power up then send the PS2_KEY_BAT  response to say it has powered up correctly (BAT = Basic Assurance Test). So you are trying to send things when the keyboard is not ready EVEN if in loop(). You need to wait to see is keyAvailable and it is an 0xAA (PS"_KEY_BAT) if powered up at same time as Arduino. Note the data iis sent at a clock speed of 10 to 17 kHZ VERY slow serial comms.

Try a delay( 800 ) before sending anything.

No doubt it gets itself rsorted when a key is pressed.

Extract from document PS"Keyboard.pdf installed in <docs>/Arduino/Libraries/extra

~~
Reset:
At power-on or software reset (see the "Reset" command) the keyboard performs a diagnostic self-test referred to as BAT (Basic Assurance Test) and loads the following default values:

  - Typematic delay 500 ms.
  - Typematic rate 10.9 cps.
  - Scan code set 2.
  - Set all keys typematic/make/break.
  - 
When entering BAT, the keyboard enables its three LED indicators, and turns them off when BAT has completed. At this time, a BAT completion code of either 0xAA (BAT successful) or 0xFC (Error) is sent to the host. This BAT completion code must be sent 500~750 milliseconds after power-on.
Many of the keyboards I've tested ignore their CLOCK and DATA lines until after the BAT completion code has been sent. Therefore, an "Inhibit" condition (CLOCK line low) may not prevent the keyboard from sending its BAT completion code.
~~~

**Comment by techpaul** [comment]
> ```
> Value 102 - Status Bits 1  Code 2
> Value FA - Status Bits 0  Code FA
> Value FA - Status Bits 0  Code FA
> Value 8102 - Status Bits 81  Code 2
> Value FA - Status Bits 0  Code FA
> Value FA - Status Bits 0  Code FA
> ```
Lets take apart your results which are VALID

| Output | | Status | Key/Value |
|:--| -- | --- | --- |
|Value 102 - Status Bits 1  Code 2| | Non-print Make code | Scroll Lock Key |
|Value FA - Status Bits 0  Code FA| | Response code FROM Keyboard | Acknowledge of set led command|
Value FA - Status Bits 0  Code FA| | Response code FROM Keyboard | Acknowledge of WHICH LED|
Value 8102 - Status Bits 81  Code 2| | Non-print BREAK code | Scroll Lock Key |
Value FA - Status Bits 0  Code FA| | Response code FROM Keyboard | Acknowledge of set led command|
Value FA - Status Bits 0  Code FA| | Response code FROM Keyboard | Acknowledge of WHICH LED|

Assumption you have set no repeat for make codes, if no break code you would not see
the Break sequence.

LED for Scroll lock should be on AFTER all that, unless lots of stages missed.

For Lock keys first press sets LED ON no matter how long key held down for, library waits for break (key release) to be received, when NEXT pressed LED is turned OFF
The acknowledges are also passed up (should have non-printing response status).
After each initial press (MAKE) of  a lock key I would expect 2 x ACKNOWLEDGE (0xFA), repeats and break codes are ignored in the code.

**Comment by techpaul** [comment]
Simple question if all keyboards work correctly and light LEDs correctly under advCodeTest what library function is not working?

You seem to be going too far into the library, please bear in mind this library has been downloaded thousands of times and I have had many people send details of things working well, so I am wondering what other thing is not working. To paraphrase a quote

"Before we start delving into Quantum Physics, should we not check the fuses one more time"

I am having trouble seeing what your actual fault symptoms are If the keyboards work correctly with advCodeTest I fail to see what I can do to fix something that appears to be working.

**Comment by pensigma** [comment]
The Scroll Lock is actually OFF after all that.
When you press the Scroll Lock, there's a MAKE code and the Scroll Lock is ON. There's no BREAK code when you release the key.
When you press the Scroll Lock again, there's a BREAK code and the Scroll Lock is OFF.

> Simple question if all keyboards work correctly and light LEDs correctly under advCodeTest what library function is not working?

I couldn't get the Num Lock to turn ON when the board & keyboard is first powered up. Now that we know why the Microsoft keyboard works, the fix is to clear the interrupt flag (at least for ARDUINO_ARCH_AVR) before calling attachInterrupt() in begin().

advCodeTest works without clearing the interrupt flag because opening the serial monitor resets the board.
As to why the Microsoft keyboard appeared to work 90% of the time, it may be because it waits ~1 second to send Scroll Lock ON OFF. So unless I call begin() right away in setup(), they're not sent by the keyboard.
I also tried clearing pending interrupt early on, but it didn't work, but it may have been due to something else.

> You seem to be going too far into the library

Believe me, I didn't want to :), except that Pause was giving the wrong code, and then I couldn't get Num Lock to turn ON.

One thing you may want to look into, in send_now(), you may want to call detachInterrupt() at the beginning, before setting variables that are also modified by ps2interrupt().

**Comment by techpaul** [comment]
First I will answer these points and have a later response after I have in my personal opinion wasted 3 hours today running tests on Uno. Mega and Due with 3 keyboards here and advCodeTest getting **IDENTICAL CORRECT RESULTS**.

> Believe me, I didn't want to :), except that Pause was giving the wrong code, and then I couldn't get Num Lock to turn ON.

Your first assumption it must be library software, I have found no cause for the LED lighting issue  (see below also), and still think you have other issues related to hardware implementation due to Nano differences and/or your wiring. causing extraneous interrupts

The readme quite clearly states what BOARDS the library has been tested on Nano and Nano Every are not listed.

> One thing you may want to look into, in send_now(), you may want to call detachInterrupt() at the beginning, before modifying variables that are also modified by ps2interrupt().

There is NO point as you do NOT understand the timings involved

- Function is not called in middle of activity but during idle or at END of keycode sequence (for Pause 8 bytes)
- The clock rate for the interrupt is 10 to 16.7 kHz which bearing in mind a 16MHz Clock works out as 950 to 1600 CPU clock cycles between clock interrupts.
- There is a minimum of 1 ms  between sucessive keycode sequences transmitted (something like 16000 cpu cycles. Even with 'n'key rollover
- Generally there is a minimum of 5 to 10 ms between fastest key sequences of different keys, due to keyboard internal debounce delays (physics)
- Fastest Typematic repeat is 30cps (33.3ms) which which means about 533,333 cpu cycles between keycode sequences.
- I have checked these timings with oscilloscope on the wiring, some scope images are in the extra folder

If this code had that much of an issue considering it was relased around February 2018 that sort out issue would have shown up LONG before now.

My day job has been for many years design electronics, software and embedded systems for paying customers to higher standards than most Arduino users understand and I would rather get back to sorting a redesign of large system for testing parts for aircraft and the  30k oreders for first round of parts. This is a large system the previous version that ran for something like 8 years 24 hours a day has some photos at bottom of this page
http://www.pcserviceselectronics.co.uk/services/designs.php

**Comment by pensigma** [comment]
Like I said, the issue is fixed by clearing pending interrupt before calling attachInterrupt() in begin() (otherwise ps2interrupt() is called immediately and stuck on receive), so let's just leave it at that.

I would have left this, but you asked me to do more tests and I obliged and reported back on my findings.

**Comment by techpaul** [comment]
You said things and stated NO patch, which sounds chip specific hack or worse
